/**
 * TypeScript declarations for Volt Component: Counter
 * Automatically generated by the Volt Wasm-GC Compiler.
 */

export interface CounterExports {
  memory: WebAssembly.Memory;
  __table: WebAssembly.Table;
  mount(root: HTMLElement | Node): void;
  increment(): void;
  decrement(): void;
  reset(): void;
  get_count(): number;
  get_step(): number;
  get_doubled(): number;
  get_quadruple(): number;
}

export interface VoltDomImports {
  createElement(tagPtr: number, tagLen: number): Element;
  createTextNode(textPtr: number, textLen: number): Text;
  setTextContent(node: Node, textPtr: number, textLen: number): void;
  setTextNumber(node: Text, val: number): void;
  setAttribute(node: Element, namePtr: number, nameLen: number, valPtr: number, valLen: number): void;
  appendChild(parent: Node, child: Node): void;
  addEventListener(node: Node, eventPtr: number, eventLen: number, fnIdx: number): void;
}

export interface VoltImports {
  dom: VoltDomImports;
  [module: string]: Record<string, Function>;
}

export declare function instantiateCounter(source: Response | Promise<Response> | ArrayBufferView | ArrayBuffer, imports: VoltImports): Promise<{ instance: { exports: CounterExports } }>;
