use crate::analysis::reactivity::ComponentPlan;
use crate::syntax::ast::Type;

pub struct DtsEmitter;

impl DtsEmitter {
    pub fn emit(plan: &ComponentPlan) -> String {
        let mut out = String::new();
        out.push_str("/**\n");
        out.push_str(&format!(" * TypeScript declarations for Volt Component: {}\n", plan.name));
        out.push_str(" * Automatically generated by the Volt Wasm-GC Compiler.\n");
        out.push_str(" */\n\n");

        out.push_str(&format!("export interface {}Exports {{\n", plan.name));
        out.push_str("  memory: WebAssembly.Memory;\n");
        out.push_str("  __table: WebAssembly.Table;\n");
        out.push_str("  mount(rootId: number): void;\n");

        // Methods
        for method in &plan.methods {
            let params = method
                .params
                .iter()
                .map(|(p, t)| format!("{}: {}", p, Self::to_ts_type(t)))
                .collect::<Vec<_>>()
                .join(", ");
            let ret = method
                .return_type
                .as_ref()
                .map(Self::to_ts_type)
                .unwrap_or_else(|| "void".into());
            out.push_str(&format!("  {}({}): {};\n", method.name, params, ret));
        }

        // Getters for signals and computeds
        for sig in &plan.signals {
            out.push_str(&format!(
                "  get_{}(): {};\n",
                sig.name,
                Self::to_ts_type(&sig.type_ann)
            ));
        }
        for comp in &plan.computeds {
            out.push_str(&format!(
                "  get_{}(): {};\n",
                comp.name,
                Self::to_ts_type(&comp.type_ann)
            ));
        }

        out.push_str("}\n\n");

        out.push_str("export interface VoltDomImports {\n");
        out.push_str("  createElement(tagPtr: number, tagLen: number): number;\n");
        out.push_str("  createTextNode(textPtr: number, textLen: number): number;\n");
        out.push_str("  setTextContent(nodeId: number, textPtr: number, textLen: number): void;\n");
        out.push_str("  setAttribute(nodeId: number, namePtr: number, nameLen: number, valPtr: number, valLen: number): void;\n");
        out.push_str("  appendChild(parentId: number, childId: number): void;\n");
        out.push_str("  addEventListener(nodeId: number, eventPtr: number, eventLen: number, fnIdx: number): void;\n");
        out.push_str("}\n\n");

        out.push_str("export interface VoltImports {\n");
        out.push_str("  dom: VoltDomImports;\n");
        out.push_str("  [module: string]: Record<string, Function>;\n");
        out.push_str("}\n\n");

        out.push_str(&format!(
            "export declare function instantiate{}(source: Response | Promise<Response> | ArrayBufferView | ArrayBuffer, imports: VoltImports): Promise<{{ instance: {{ exports: {}Exports }} }}>;\n",
            plan.name, plan.name
        ));

        out
    }

    fn to_ts_type(t: &Type) -> String {
        match t {
            Type::I32 | Type::I64 | Type::U32 | Type::U64 | Type::F32 | Type::F64 => {
                "number".to_string()
            }
            Type::Bool => "boolean".to_string(),
            Type::String => "string".to_string(),
            Type::Void => "void".to_string(),
            Type::Option(inner) => format!("{} | null | undefined", Self::to_ts_type(inner)),
            Type::Result(ok, err) => {
                format!(
                    "{{ ok: true, value: {} }} | {{ ok: false, error: {} }}",
                    Self::to_ts_type(ok),
                    Self::to_ts_type(err)
                )
            }
            Type::Custom(name) => name.clone(),
        }
    }
}
